dataSet:
  source:
    localCopy:
      path: src/main/resources/temp
      prefix: dataSetSource
    persist:
      enabled: true
---
spring:
  profiles: european-central-bank
dataSet:
  baseCurrency: EUR
  source:
    url: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-sdmx.xml
    localCopy:
      extension: xml
  update:
    url: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
  schedule:
    newRates:
      timeZone: GMT
      cronPatternTrigger: 0 0 16 * * MON-FRI
